// Code generated by goctl. DO NOT EDIT.
// Source: sku.proto

package server

import (
	"context"

	"wechat-merchant-go/internal/logic/skuservice"
	"wechat-merchant-go/internal/svc"
	"wechat-merchant-go/pb/sku"
)

type SkuServiceServer struct {
	svcCtx *svc.ServiceContext
	sku.UnimplementedSkuServiceServer
}

func NewSkuServiceServer(svcCtx *svc.ServiceContext) *SkuServiceServer {
	return &SkuServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SkuServiceServer) GetSkuInfo(ctx context.Context, in *sku.SkuReq) (*sku.SkuResp, error) {
	l := skuservicelogic.NewGetSkuInfoLogic(ctx, s.svcCtx)
	return l.GetSkuInfo(in)
}

func (s *SkuServiceServer) CreateSkuInfo(ctx context.Context, in *sku.CreateSkuReq) (*sku.CommonRsp, error) {
	l := skuservicelogic.NewCreateSkuInfoLogic(ctx, s.svcCtx)
	return l.CreateSkuInfo(in)
}
