// Code generated by goctl. DO NOT EDIT.
// Source: sku.proto

package server

import (
	"context"

	"wechat-merchant-go/internal/logic/shopservice"
	"wechat-merchant-go/internal/svc"
	"wechat-merchant-go/pb/sku"
)

type ShopServiceServer struct {
	svcCtx *svc.ServiceContext
	sku.UnimplementedShopServiceServer
}

func NewShopServiceServer(svcCtx *svc.ServiceContext) *ShopServiceServer {
	return &ShopServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopServiceServer) GetShopInfo(ctx context.Context, in *sku.GetShopInfoReq) (*sku.GetShopInfoResp, error) {
	l := shopservicelogic.NewGetShopInfoLogic(ctx, s.svcCtx)
	return l.GetShopInfo(in)
}

func (s *ShopServiceServer) CreateShopInfo(ctx context.Context, in *sku.CreateShopReq) (*sku.CommonRsp, error) {
	l := shopservicelogic.NewCreateShopInfoLogic(ctx, s.svcCtx)
	return l.CreateShopInfo(in)
}

func (s *ShopServiceServer) UpdateShopInfo(ctx context.Context, in *sku.UpdateShopReq) (*sku.CommonRsp, error) {
	l := shopservicelogic.NewUpdateShopInfoLogic(ctx, s.svcCtx)
	return l.UpdateShopInfo(in)
}
