// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"wechat-merchant-go/internal/dao/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.SkuInventoryTab{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.SkuInventoryTab{}) fail: %s", err)
	}
}

func Test_skuInventoryTabQuery(t *testing.T) {
	skuInventoryTab := newSkuInventoryTab(_gen_test_db)
	skuInventoryTab = *skuInventoryTab.As(skuInventoryTab.TableName())
	_do := skuInventoryTab.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(skuInventoryTab.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <sku_inventory_tab> fail:", err)
		return
	}

	_, ok := skuInventoryTab.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from skuInventoryTab success")
	}

	err = _do.Create(&model.SkuInventoryTab{})
	if err != nil {
		t.Error("create item in table <sku_inventory_tab> fail:", err)
	}

	err = _do.Save(&model.SkuInventoryTab{})
	if err != nil {
		t.Error("create item in table <sku_inventory_tab> fail:", err)
	}

	err = _do.CreateInBatches([]*model.SkuInventoryTab{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Select(skuInventoryTab.ALL).Take()
	if err != nil {
		t.Error("Take() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <sku_inventory_tab> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.SkuInventoryTab{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Select(skuInventoryTab.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Select(skuInventoryTab.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <sku_inventory_tab> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.ScanByPage(&model.SkuInventoryTab{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <sku_inventory_tab> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <sku_inventory_tab> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <sku_inventory_tab> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <sku_inventory_tab> fail:", err)
	}
}
