// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itemInfoTabFieldNames          = builder.RawFieldNames(&ItemInfoTab{})
	itemInfoTabRows                = strings.Join(itemInfoTabFieldNames, ",")
	itemInfoTabRowsExpectAutoSet   = strings.Join(stringx.Remove(itemInfoTabFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	itemInfoTabRowsWithPlaceHolder = strings.Join(stringx.Remove(itemInfoTabFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	itemInfoTabModel interface {
		Insert(ctx context.Context, data *ItemInfoTab) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ItemInfoTab, error)
		FindOneByItemId(ctx context.Context, itemId uint64) (*ItemInfoTab, error)
		Update(ctx context.Context, data *ItemInfoTab) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultItemInfoTabModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ItemInfoTab struct {
		Id           uint64 `db:"id"`
		ItemId       uint64 `db:"item_id"`
		ItemName     string `db:"item_name"`
		CategoryId   uint64 `db:"category_id"`
		CategoryName string `db:"category_name"`
		ShopId       uint64 `db:"shop_id"`
		Ctime        uint64 `db:"ctime"`
		Mtime        uint64 `db:"mtime"`
	}
)

func newItemInfoTabModel(conn sqlx.SqlConn) *defaultItemInfoTabModel {
	return &defaultItemInfoTabModel{
		conn:  conn,
		table: "`item_info_tab`",
	}
}

func (m *defaultItemInfoTabModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultItemInfoTabModel) FindOne(ctx context.Context, id uint64) (*ItemInfoTab, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itemInfoTabRows, m.table)
	var resp ItemInfoTab
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItemInfoTabModel) FindOneByItemId(ctx context.Context, itemId uint64) (*ItemInfoTab, error) {
	var resp ItemInfoTab
	query := fmt.Sprintf("select %s from %s where `item_id` = ? limit 1", itemInfoTabRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, itemId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItemInfoTabModel) Insert(ctx context.Context, data *ItemInfoTab) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, itemInfoTabRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ItemId, data.ItemName, data.CategoryId, data.CategoryName, data.ShopId, data.Ctime, data.Mtime)
	return ret, err
}

func (m *defaultItemInfoTabModel) Update(ctx context.Context, newData *ItemInfoTab) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itemInfoTabRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ItemId, newData.ItemName, newData.CategoryId, newData.CategoryName, newData.ShopId, newData.Ctime, newData.Mtime, newData.Id)
	return err
}

func (m *defaultItemInfoTabModel) tableName() string {
	return m.table
}
