// Code generated by goctl. DO NOT EDIT.
// Source: sku.proto

package server

import (
	"context"

	"wechat-merchant-go/internal/logic/skuinventoryservice"
	"wechat-merchant-go/internal/svc"
	"wechat-merchant-go/pb/sku"
)

type SkuInventoryServiceServer struct {
	svcCtx *svc.ServiceContext
	sku.UnimplementedSkuInventoryServiceServer
}

func NewSkuInventoryServiceServer(svcCtx *svc.ServiceContext) *SkuInventoryServiceServer {
	return &SkuInventoryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SkuInventoryServiceServer) GetSkuInventoryInfo(ctx context.Context, in *sku.SkuInventoryReq) (*sku.SkuInventoryResp, error) {
	l := skuinventoryservicelogic.NewGetSkuInventoryInfoLogic(ctx, s.svcCtx)
	return l.GetSkuInventoryInfo(in)
}

func (s *SkuInventoryServiceServer) UpdateSkuInventoryInfo(ctx context.Context, in *sku.UpdateSkuInventoryInfoReq) (*sku.CommonRsp, error) {
	l := skuinventoryservicelogic.NewUpdateSkuInventoryInfoLogic(ctx, s.svcCtx)
	return l.UpdateSkuInventoryInfo(in)
}
