// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: pb/sku.proto

package sku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{0}
}

func (x *CommonRsp) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SkuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId      []string `protobuf:"bytes,1,rep,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	PageNumber uint64   `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize   uint64   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *SkuReq) Reset() {
	*x = SkuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuReq) ProtoMessage() {}

func (x *SkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuReq.ProtoReflect.Descriptor instead.
func (*SkuReq) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{1}
}

func (x *SkuReq) GetSkuId() []string {
	if x != nil {
		return x.SkuId
	}
	return nil
}

func (x *SkuReq) GetPageNumber() uint64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SkuReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SkuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   []*SkuInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total  uint64     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SkuResp) Reset() {
	*x = SkuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuResp) ProtoMessage() {}

func (x *SkuResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuResp.ProtoReflect.Descriptor instead.
func (*SkuResp) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{2}
}

func (x *SkuResp) GetCommon() *CommonRsp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SkuResp) GetData() []*SkuInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SkuResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SkuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId       string `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SkuName     string `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	SkuImage    string `protobuf:"bytes,3,opt,name=sku_image,json=skuImage,proto3" json:"sku_image,omitempty"`
	ItemId      uint32 `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName    string `protobuf:"bytes,5,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ProductId   uint32 `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Ctime       uint64 `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime       uint64 `protobuf:"varint,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
}

func (x *SkuInfo) Reset() {
	*x = SkuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfo) ProtoMessage() {}

func (x *SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfo.ProtoReflect.Descriptor instead.
func (*SkuInfo) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{3}
}

func (x *SkuInfo) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *SkuInfo) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *SkuInfo) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *SkuInfo) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SkuInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SkuInfo) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SkuInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SkuInfo) GetCtime() uint64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *SkuInfo) GetMtime() uint64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

// 此处应该还要修改
type CreateOrUpdateSkuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId    string `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SkuName  string `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	SkuImage string `protobuf:"bytes,3,opt,name=sku_image,json=skuImage,proto3" json:"sku_image,omitempty"`
	SkuCount string `protobuf:"bytes,4,opt,name=sku_count,json=skuCount,proto3" json:"sku_count,omitempty"`
}

func (x *CreateOrUpdateSkuReq) Reset() {
	*x = CreateOrUpdateSkuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateSkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateSkuReq) ProtoMessage() {}

func (x *CreateOrUpdateSkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateSkuReq.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateSkuReq) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrUpdateSkuReq) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *CreateOrUpdateSkuReq) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CreateOrUpdateSkuReq) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *CreateOrUpdateSkuReq) GetSkuCount() string {
	if x != nil {
		return x.SkuCount
	}
	return ""
}

type SkuInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId []string `protobuf:"bytes,1,rep,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
}

func (x *SkuInventoryReq) Reset() {
	*x = SkuInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventoryReq) ProtoMessage() {}

func (x *SkuInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventoryReq.ProtoReflect.Descriptor instead.
func (*SkuInventoryReq) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{5}
}

func (x *SkuInventoryReq) GetSkuId() []string {
	if x != nil {
		return x.SkuId
	}
	return nil
}

type SkuInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonRsp          `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   []*SkuInventoryInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SkuInventoryResp) Reset() {
	*x = SkuInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventoryResp) ProtoMessage() {}

func (x *SkuInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventoryResp.ProtoReflect.Descriptor instead.
func (*SkuInventoryResp) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{6}
}

func (x *SkuInventoryResp) GetCommon() *CommonRsp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SkuInventoryResp) GetData() []*SkuInventoryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type SkuInventoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId        string `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	InventoryQty uint64 `protobuf:"varint,2,opt,name=inventory_qty,json=inventoryQty,proto3" json:"inventory_qty,omitempty"`
	DamageQty    uint64 `protobuf:"varint,3,opt,name=damage_qty,json=damageQty,proto3" json:"damage_qty,omitempty"`
}

func (x *SkuInventoryInfo) Reset() {
	*x = SkuInventoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sku_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventoryInfo) ProtoMessage() {}

func (x *SkuInventoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sku_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventoryInfo.ProtoReflect.Descriptor instead.
func (*SkuInventoryInfo) Descriptor() ([]byte, []int) {
	return file_pb_sku_proto_rawDescGZIP(), []int{7}
}

func (x *SkuInventoryInfo) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *SkuInventoryInfo) GetInventoryQty() uint64 {
	if x != nil {
		return x.InventoryQty
	}
	return 0
}

func (x *SkuInventoryInfo) GetDamageQty() uint64 {
	if x != nil {
		return x.DamageQty
	}
	return 0
}

var File_pb_sku_proto protoreflect.FileDescriptor

var file_pb_sku_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x73, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x73, 0x6b, 0x75, 0x22, 0x31, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5d, 0x0a, 0x06, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71,
	0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x70, 0x61,
	0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x69, 0x0a, 0x07, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x53, 0x6b, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0xfc, 0x01, 0x0a, 0x07, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b,
	0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x82, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b,
	0x75, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x6b, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0f, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x22, 0x65,
	0x0a, 0x10, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x53,
	0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6d, 0x0a, 0x10, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x71, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x51, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x51, 0x74, 0x79, 0x32, 0xea, 0x01, 0x0a, 0x0a, 0x53, 0x6b, 0x75, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0b, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e,
	0x73, 0x6b, 0x75, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x73, 0x6b, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x42, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x73, 0x6b, 0x75, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73, 0x6b, 0x75,
	0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x2c, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x73, 0x6b, 0x75, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x05, 0x2e, 0x2f, 0x73, 0x6b, 0x75, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_sku_proto_rawDescOnce sync.Once
	file_pb_sku_proto_rawDescData = file_pb_sku_proto_rawDesc
)

func file_pb_sku_proto_rawDescGZIP() []byte {
	file_pb_sku_proto_rawDescOnce.Do(func() {
		file_pb_sku_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_sku_proto_rawDescData)
	})
	return file_pb_sku_proto_rawDescData
}

var file_pb_sku_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_sku_proto_goTypes = []interface{}{
	(*CommonRsp)(nil),            // 0: sku.CommonRsp
	(*SkuReq)(nil),               // 1: sku.SkuReq
	(*SkuResp)(nil),              // 2: sku.SkuResp
	(*SkuInfo)(nil),              // 3: sku.SkuInfo
	(*CreateOrUpdateSkuReq)(nil), // 4: sku.CreateOrUpdateSkuReq
	(*SkuInventoryReq)(nil),      // 5: sku.SkuInventoryReq
	(*SkuInventoryResp)(nil),     // 6: sku.SkuInventoryResp
	(*SkuInventoryInfo)(nil),     // 7: sku.SkuInventoryInfo
}
var file_pb_sku_proto_depIdxs = []int32{
	0, // 0: sku.SkuResp.common:type_name -> sku.CommonRsp
	3, // 1: sku.SkuResp.data:type_name -> sku.SkuInfo
	0, // 2: sku.SkuInventoryResp.common:type_name -> sku.CommonRsp
	7, // 3: sku.SkuInventoryResp.data:type_name -> sku.SkuInventoryInfo
	1, // 4: sku.SkuService.GetSkuInfo:input_type -> sku.SkuReq
	4, // 5: sku.SkuService.CreateSkuInfo:input_type -> sku.CreateOrUpdateSkuReq
	4, // 6: sku.SkuService.Update:input_type -> sku.CreateOrUpdateSkuReq
	5, // 7: sku.SkuService.GetSkuInventoryInfo:input_type -> sku.SkuInventoryReq
	2, // 8: sku.SkuService.GetSkuInfo:output_type -> sku.SkuResp
	0, // 9: sku.SkuService.CreateSkuInfo:output_type -> sku.CommonRsp
	0, // 10: sku.SkuService.Update:output_type -> sku.CommonRsp
	6, // 11: sku.SkuService.GetSkuInventoryInfo:output_type -> sku.SkuInventoryResp
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_sku_proto_init() }
func file_pb_sku_proto_init() {
	if File_pb_sku_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_sku_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateSkuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sku_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_sku_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sku_proto_goTypes,
		DependencyIndexes: file_pb_sku_proto_depIdxs,
		MessageInfos:      file_pb_sku_proto_msgTypes,
	}.Build()
	File_pb_sku_proto = out.File
	file_pb_sku_proto_rawDesc = nil
	file_pb_sku_proto_goTypes = nil
	file_pb_sku_proto_depIdxs = nil
}
