// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: sku.proto

package sku

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SkuService_GetSkuInfo_FullMethodName    = "/sku.SkuService/GetSkuInfo"
	SkuService_CreateSkuInfo_FullMethodName = "/sku.SkuService/CreateSkuInfo"
	SkuService_Update_FullMethodName        = "/sku.SkuService/Update"
)

// SkuServiceClient is the client API for SkuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkuServiceClient interface {
	GetSkuInfo(ctx context.Context, in *SkuReq, opts ...grpc.CallOption) (*SkuResp, error)
	CreateSkuInfo(ctx context.Context, in *CreateOrUpdateSkuReq, opts ...grpc.CallOption) (*CommonRsp, error)
	Update(ctx context.Context, in *CreateOrUpdateSkuReq, opts ...grpc.CallOption) (*CommonRsp, error)
}

type skuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkuServiceClient(cc grpc.ClientConnInterface) SkuServiceClient {
	return &skuServiceClient{cc}
}

func (c *skuServiceClient) GetSkuInfo(ctx context.Context, in *SkuReq, opts ...grpc.CallOption) (*SkuResp, error) {
	out := new(SkuResp)
	err := c.cc.Invoke(ctx, SkuService_GetSkuInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) CreateSkuInfo(ctx context.Context, in *CreateOrUpdateSkuReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, SkuService_CreateSkuInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) Update(ctx context.Context, in *CreateOrUpdateSkuReq, opts ...grpc.CallOption) (*CommonRsp, error) {
	out := new(CommonRsp)
	err := c.cc.Invoke(ctx, SkuService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuServiceServer is the server API for SkuService service.
// All implementations must embed UnimplementedSkuServiceServer
// for forward compatibility
type SkuServiceServer interface {
	GetSkuInfo(context.Context, *SkuReq) (*SkuResp, error)
	CreateSkuInfo(context.Context, *CreateOrUpdateSkuReq) (*CommonRsp, error)
	Update(context.Context, *CreateOrUpdateSkuReq) (*CommonRsp, error)
	mustEmbedUnimplementedSkuServiceServer()
}

// UnimplementedSkuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkuServiceServer struct {
}

func (UnimplementedSkuServiceServer) GetSkuInfo(context.Context, *SkuReq) (*SkuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkuInfo not implemented")
}
func (UnimplementedSkuServiceServer) CreateSkuInfo(context.Context, *CreateOrUpdateSkuReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSkuInfo not implemented")
}
func (UnimplementedSkuServiceServer) Update(context.Context, *CreateOrUpdateSkuReq) (*CommonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSkuServiceServer) mustEmbedUnimplementedSkuServiceServer() {}

// UnsafeSkuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkuServiceServer will
// result in compilation errors.
type UnsafeSkuServiceServer interface {
	mustEmbedUnimplementedSkuServiceServer()
}

func RegisterSkuServiceServer(s grpc.ServiceRegistrar, srv SkuServiceServer) {
	s.RegisterService(&SkuService_ServiceDesc, srv)
}

func _SkuService_GetSkuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).GetSkuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkuService_GetSkuInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).GetSkuInfo(ctx, req.(*SkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_CreateSkuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).CreateSkuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkuService_CreateSkuInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).CreateSkuInfo(ctx, req.(*CreateOrUpdateSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkuService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).Update(ctx, req.(*CreateOrUpdateSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SkuService_ServiceDesc is the grpc.ServiceDesc for SkuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sku.SkuService",
	HandlerType: (*SkuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSkuInfo",
			Handler:    _SkuService_GetSkuInfo_Handler,
		},
		{
			MethodName: "CreateSkuInfo",
			Handler:    _SkuService_CreateSkuInfo_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SkuService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sku.proto",
}
