// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemInfoTab = "item_info_tab"

// ItemInfoTab mapped from table <item_info_tab>
type ItemInfoTab struct {
	ID           uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ItemID       uint32 `gorm:"column:item_id;not null" json:"item_id"`
	ItemName     string `gorm:"column:item_name;not null" json:"item_name"`
	CategoryID   uint32 `gorm:"column:category_id;not null" json:"category_id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
	ShopID       uint32 `gorm:"column:shop_id;not null" json:"shop_id"`
	Ctime        uint32 `gorm:"column:ctime;not null" json:"ctime"`
	Mtime        uint32 `gorm:"column:mtime;not null" json:"mtime"`
}

// TableName ItemInfoTab's table name
func (*ItemInfoTab) TableName() string {
	return TableNameItemInfoTab
}
