// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameShopInfoTab = "shop_info_tab"

// ShopInfoTab mapped from table <shop_info_tab>
type ShopInfoTab struct {
	ID       uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ShopID   uint32 `gorm:"column:shop_id;not null" json:"shop_id"`
	ShopName string `gorm:"column:shop_name;not null" json:"shop_name"`
	Ctime    uint32 `gorm:"column:ctime;not null" json:"ctime"`
	Mtime    uint32 `gorm:"column:mtime;not null" json:"mtime"`
}

// TableName ShopInfoTab's table name
func (*ShopInfoTab) TableName() string {
	return TableNameShopInfoTab
}
