// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkuInfoTab = "sku_info_tab"

// SkuInfoTab mapped from table <sku_info_tab>
type SkuInfoTab struct {
	ID           uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SkuID        string `gorm:"column:sku_id;not null" json:"sku_id"`
	SkuName      string `gorm:"column:sku_name;not null" json:"sku_name"`
	ItemID       int32  `gorm:"column:item_id;not null" json:"item_id"`
	ItemName     string `gorm:"column:item_name;not null" json:"item_name"`
	ProductID    uint32 `gorm:"column:product_id;not null" json:"product_id"`
	ProductName  string `gorm:"column:product_name;not null" json:"product_name"`
	CategoryID   uint32 `gorm:"column:category_id;not null" json:"category_id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
	ShopID       uint32 `gorm:"column:shop_id;not null" json:"shop_id"`
	Ctime        uint32 `gorm:"column:ctime;not null" json:"ctime"`
	Mtime        uint32 `gorm:"column:mtime;not null" json:"mtime"`
}

// TableName SkuInfoTab's table name
func (*SkuInfoTab) TableName() string {
	return TableNameSkuInfoTab
}
